apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
  labels:
    app: sample-app
    managed-by: harness-gitops
  annotations:
    description: "Simple example: Secret expressions directly in Secret manifest"
type: Opaque
stringData:
  # ========================================
  # HARNESS SECRET EXPRESSIONS
  # ========================================
  # These expressions reference secrets stored in HashiCorp Vault
  # and managed through Harness at different scopes.
  
  # Account-level secret (Account Settings → Secrets)
  # Syntax: <+secrets.getValue("account.SECRET_ID")>
  vault-secret: <+secrets.getValue("vaultSecret")>
  
  # Organization-level secret (Org Settings → Secrets)
  # Syntax: <+secrets.getValue("org.SECRET_ID")>
  api-key: <+secrets.getValue("apiKey")>
  
  # Project-level secret (Project Settings → Secrets)
  # Syntax: <+secrets.getValue("SECRET_ID")>
  db-password: <+secrets.getValue("dbPassword")>
  
  # Additional project-level secrets
  app-secret: <+secrets.getValue("appSecret")>
  redis-password: <+secrets.getValue("redisPassword")>

