apiVersion: v2
name: sample-app
description: Sample Helm chart demonstrating Harness Secret Expressions in values.yaml
type: application
version: 1.0.0
appVersion: "1.0"
home: https://developer.harness.io/docs/continuous-delivery/gitops/
sources:
  - https://github.com/harness-community/Gitops-Samples
